### ISSUE TITLE
What's the recommended Disk Space for CodeSpaces?

### ISSUE THREAD

**Issue by rido-min** [Azure-Samples/explore-iot-operations#41]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy AIO to CodeSpaces

### Any log messages given by the failure
>
<img width="340" alt="image" src="https://github.com/Azure-Samples/explore-iot-operations/assets/14916339/25034a2a-42f6-4d11-a15a-aa4cdb996937">

### Expected/desired behavior
> CodeSpaces is configured with enough Memory and Disk

### OS and Version?
> CodeSpaces
### Versions
> Public Preview

**Comment by rido-min** [comment]
I found how to clean disk space in codespaces, however the k3d node is evicting most of the pods because it reports as DiskPressure.

I think the k3d cluster needs to be configured with appropriate disk space to handle the AIO deployment and additional workloads.

**Comment by jlian** [comment]
We have a minimum codespace deployment storage set as 32GB which in my experience should be enough

https://github.com/Azure-Samples/explore-iot-operations/blob/9f4bef49e2aa84b6269914140e634900f33bc23e/.devcontainer/devcontainer.json#L10-L14

I've seen the low space issue before and it was never clear what causes it since it goes away when I do a full codespace rebuild.

Are you seeing this happen on a completely fresh deployment, or sometime afterwards?

**Comment by rido-min** [comment]
I have seen this behavior more than once in a fresh deployment, I'd say 32Gb is not enough once ARC and AzMonitor are enabled in the cluster.

**Comment by jlian** [comment]
Hmm ok. It's easy for me to change the default to be 64GB. You can also resize your codespace in the UI https://docs.github.com/en/codespaces/customizing-your-codespace/changing-the-machine-type-for-your-codespace

**Comment by ryanwinter** [comment]
What happened to increasing this? I see you closed the PR @jlian

**Comment by ryanwinter** [comment]
Increased the codespaces side.
